#!/bin/sh
# Asterisk entrypoint — auto-detects host IP for NAT/RTP config
# Generates /etc/asterisk/pjsip_transport.conf before starting Asterisk.
#
# IP detection priority:
#   1. EXTERNAL_IP env var (explicit override — use for Tailscale/VPN/custom)
#   2. STUN query (auto-detect public IP — works for most setups)
#   3. host.docker.internal (Docker Desktop fallback)
#   4. Default gateway (Linux Docker fallback)

set -e

# EXTERNAL_IP may be comma-separated (e.g. "100.96.49.117,10.0.0.7").
# Asterisk only accepts a single IP — use the first one for NAT config.
NAT_IP=$(echo "$EXTERNAL_IP" | cut -d',' -f1)

# STUN auto-detection: query a public STUN server to discover our external IP.
# This works for cloud/VPS deployments and most home networks.
if [ -z "$NAT_IP" ]; then
  # Use Asterisk's built-in res_stun_monitor or a simple STUN client if available.
  # Lightweight approach: parse the mapped address from a raw STUN binding request.
  # Google and Cloudflare STUN servers are reliable.
  for STUN_SERVER in stun.l.google.com:19302 stun.cloudflare.com:3478; do
    # Try a quick UDP STUN binding request using python (available in most images)
    NAT_IP=$(python3 -c "
import socket, struct, os
host, port = '$STUN_SERVER'.split(':')
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(3)
tid = os.urandom(12)
msg = struct.pack('!HH', 0x0001, 0) + b'\x21\x12\xa4\x42' + tid
sock.sendto(msg, (host, int(port)))
data, _ = sock.recvfrom(1024)
# Parse MAPPED-ADDRESS or XOR-MAPPED-ADDRESS
i = 20
while i < len(data) - 4:
    atype, alen = struct.unpack('!HH', data[i:i+4])
    if atype in (0x0001, 0x8020, 0x0020) and alen >= 8:
        family = data[i+5]
        if family == 1:  # IPv4
            if atype in (0x0020, 0x8020):  # XOR-MAPPED
                xport = struct.unpack('!H', data[i+6:i+8])[0] ^ 0x2112
                xip = struct.unpack('!I', data[i+8:i+12])[0] ^ 0x2112A442
                print(socket.inet_ntoa(struct.pack('!I', xip)))
            else:
                print(socket.inet_ntoa(data[i+8:i+12]))
            break
    i += 4 + alen
sock.close()
" 2>/dev/null) && break
  done
  if [ -n "$NAT_IP" ]; then
    echo "Asterisk NAT: detected external IP via STUN: $NAT_IP"
  fi
fi

if [ -z "$NAT_IP" ]; then
  # Fallback: resolve host.docker.internal to IPv4 (Docker Desktop)
  NAT_IP=$(getent ahostsv4 host.docker.internal 2>/dev/null | head -1 | awk '{print $1}')
fi

if [ -z "$NAT_IP" ]; then
  # Last resort: Docker default gateway
  NAT_IP=$(ip route 2>/dev/null | grep default | awk '{print $3}')
fi

if [ -z "$NAT_IP" ]; then
  echo "WARNING: Could not detect host IP. SIP NAT/RTP may not work."
  echo "Set EXTERNAL_IP env var in docker-compose.yml or .env file."
  NAT_IP="0.0.0.0"
fi

echo "Asterisk NAT: external_media_address=$NAT_IP"

# Generate transport config
cat > /etc/asterisk/pjsip_transport.conf << EOF
; Auto-generated by entrypoint.sh — do not edit
; Host IP: $NAT_IP
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=$NAT_IP
external_signaling_address=$NAT_IP
EOF

# Install Asterisk core sounds if not already present.
# Downloaded to /data/sounds (persistent volume), symlinked into Asterisk's path.
SOUNDS_DATA="/data/sounds/en"
SOUNDS_DIR="/var/lib/asterisk/sounds/en"
SOUNDS_URL="https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-en-ulaw-current.tar.gz"

if [ ! -f "$SOUNDS_DATA/vm-intro.ulaw" ]; then
  echo "Downloading Asterisk core sound files..."
  mkdir -p "$SOUNDS_DATA"
  if curl -sSLk "$SOUNDS_URL" | tar xz -C "$SOUNDS_DATA"; then
    echo "Sound files installed to $SOUNDS_DATA"
  else
    echo "WARNING: Failed to download sound files. Voicemail prompts will be silent."
  fi
fi

# Symlink persistent sounds into Asterisk's expected path
mkdir -p /var/lib/asterisk/sounds
ln -sfn "$SOUNDS_DATA" "$SOUNDS_DIR"

# Generate voiceworker trunk config if VOICEWORKER_HOST is set
if [ -n "$VOICEWORKER_HOST" ]; then
  echo "Generating voiceworker trunk config for $VOICEWORKER_HOST"

  # Use container's network IPv4 as media_address (correct for Docker networks)
  # Filter for IPv4 only — hostname -i may return IPv6 addresses
  CONTAINER_IP=$(hostname -i 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
  if [ -z "$CONTAINER_IP" ]; then
    CONTAINER_IP="$NAT_IP"
  fi

  cat > /etc/asterisk/pjsip_voiceworker.conf << EOF
; Auto-generated by entrypoint.sh — do not edit
; VOICEWORKER_HOST=$VOICEWORKER_HOST

[voiceworker-aor]
type=aor
contact=sip:${VOICEWORKER_HOST}

[voiceworker-trunk]
type=endpoint
transport=transport-udp
context=from-voiceworker
disallow=all
allow=ulaw,alaw
aors=voiceworker-aor
media_address=${CONTAINER_IP}
EOF

  # Generate voiceworker dialplan route
  VOICEWORKER_EXTEN=${VOICEWORKER_EXTEN:-2000}
  cat > /etc/asterisk/extensions_voiceworker.conf << EOF
; Auto-generated by entrypoint.sh — do not edit
; Routes extension $VOICEWORKER_EXTEN to voiceworker trunk ($VOICEWORKER_HOST)

[from-internal](+)
exten => ${VOICEWORKER_EXTEN},1,NoOp(Calling voiceworker at ${VOICEWORKER_HOST})
 same => n,Dial(PJSIP/\${EXTEN}@voiceworker-trunk,30)
 same => n,Hangup()
EOF

  echo "Voiceworker: extension $VOICEWORKER_EXTEN -> $VOICEWORKER_HOST (media_address=$CONTAINER_IP)"
else
  # Create empty config files (sorcery.conf references pjsip_voiceworker.conf)
  : > /etc/asterisk/pjsip_voiceworker.conf
  rm -f /etc/asterisk/extensions_voiceworker.conf
fi

# Start Asterisk with original arguments
exec /usr/sbin/asterisk "$@"
